In [1]:
 import pandas as pd

In [2]:
pd.read_csv()

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'

In [3]:
pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/dataset/master/laptops.csv')

HTTPError: HTTP Error 404: Not Found

In [4]:
url = "https://raw.githubusercontent.com/alexeygrigorev/dataset/master/laptops.csv?raw=1"
df = pd.read_csv(url)
df.head()

HTTPError: HTTP Error 404: Not Found

In [5]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/alexeygrigorev/dataset/master/laptops.csv"
response = requests.get(url)

df = pd.read_csv(StringIO(response.text))
df.head()

Empty DataFrame
Columns: [404: Not Found]
Index: []

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [11]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369